# Exercise 1

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## PART A - NumPy

* **(10 points)** Create a random dataset with 1000 rows and 6 columns by generating the columns one at a time and then concatenating them to create the dataset.

In [2]:
np.random.RandomState(42)

dataset = np.random.randn(1000, 1)

for col in range(5):
    dataset = np.concatenate([dataset, np.random.randint(-10, 10, size=(1000, 1))], axis=1)
    
print(dataset.shape)
print(dataset)

(1000, 6)
[[  0.18171411  -9.          -4.          -1.          -9.
   -6.        ]
 [  1.44424247   1.           4.           3.          -8.
    2.        ]
 [  0.56254893   0.           7.          -4.          -6.
   -9.        ]
 ...
 [  0.06694501   9.         -10.          -1.          -1.
    9.        ]
 [ -0.2515041    6.           2.         -10.           4.
   -4.        ]
 [  2.03804292 -10.          -4.           7.          -5.
   -5.        ]]


* **(8 points)** Shuffle the dataset.

In [3]:
np.random.shuffle(dataset)

print(dataset.shape)
print(dataset)

(1000, 6)
[[-0.10015028  7.         -9.          5.          7.         -6.        ]
 [ 0.14199505  0.         -5.          6.         -6.          6.        ]
 [ 1.56097254  4.         -1.          7.         -8.         -9.        ]
 ...
 [-1.32649761  4.          1.         -3.         -7.         -1.        ]
 [-1.32092938 -7.          8.          6.          7.          0.        ]
 [-0.22686072  9.          2.          4.          4.          7.        ]]


* **(10 points)** Split it using a 60/25/15 split into three sets: training, validation and test.

In [4]:
#training, validation, test size percentages
training, validation, test = 0.6, 0.25, 0.15

#get the 2 split indexes (split at 60% and 85%)
split_ndx1, split_ndx2 = int(training * len(dataset)), int((training + validation) * len(dataset))

training_set, validation_set, test_set = dataset[0:split_ndx1,:], dataset[split_ndx1:split_ndx2,:], dataset[split_ndx2:,:]
print(f'''
Training Set shape: {training_set.shape}
Validation Set shape: {validation_set.shape}
Test Set shape: {test_set.shape}
''')


Training Set shape: (600, 6)
Validation Set shape: (250, 6)
Test Set shape: (150, 6)



* **(7 points)** Standardize every column in the training set by subtracting every column by its mean and dividing the result by its standard deviation.

In [5]:
means = []
stds = []

for col in range(training_set.shape[1]):
    col_mean = training_set[:,col].mean()
    col_std = training_set[:,col].std()
    
    means.append(col_mean)
    stds.append(col_std)
    
    training_set[:,col] -= col_mean
    training_set[:,col] /= col_std
    
print(training_set.shape)
print(training_set)

(600, 6)
[[-0.09789617  1.32225337 -1.49698429  0.98141621  1.33387209 -0.94818383]
 [ 0.15290275  0.1099713  -0.8073946   1.15455638 -0.96489113  1.14083807]
 [ 1.6225905   0.80270391 -0.11780491  1.32769656 -1.318547   -1.47043931]
 ...
 [ 0.4900142   0.62952076  0.39938736 -0.57684534 -0.78806319 -0.94818383]
 [ 1.58437154 -1.44867707  1.08897706 -0.92312569 -1.318547    0.79266776]
 [ 1.03282978 -0.92912761  1.4337719  -1.61568638  0.27290445 -0.2518432 ]]


* **(5 points)** Do the same with validation and test sets but using the mean and standard deviation from the training set.

In [6]:
for col in range(training_set.shape[1]):
    #validation
    validation_set[:,col] -= means[col]
    validation_set[:,col] /= stds[col]
    
    #test set
    test_set[:,col] -= means[col]
    test_set[:,col] /= stds[col]
    
print(validation_set.shape)
print(test_set.shape)

(250, 6)
(150, 6)


## PART B - Pandas
* **(6 points)** Take the 1000-row dataset you created in the Numpy part and create a DataFrame with it. Give the columns the names `a` to `f`.

In [7]:
df = pd.DataFrame(dataset, columns=['a', 'b', 'c', 'd', 'e', 'f'])
df.head()

a         b         c         d         e         f
0 -0.097896  1.322253 -1.496984  0.981416  1.333872 -0.948184
1  0.152903  0.109971 -0.807395  1.154556 -0.964891  1.140838
2  1.622590  0.802704 -0.117805  1.327697 -1.318547 -1.470439
3 -0.552783  0.975887 -0.290202  1.500837  0.096077  1.314923
4 -1.011904 -0.409578  1.433772  0.115715 -1.672203  1.489008

* **(6 points)** Shuffle the DataFrame.

In [8]:
# TODO

* **(8 points)** Break it using a 60/25/15 split into three dataframes: training, validation, and test.

In [9]:
# TODO

* **(6 points)** Standardize every column in the training dataframe by subtracting every column by its mean and dividing the result by its standard deviation. Do the same with validation and test dataframes but using the mean and standard deviation from the training dataframe.

In [10]:
# TODO

* **(4 points)** Save all three dataframes into their own `.csv` files.

In [11]:
# TODO

## PART C - Matplotlib

* **(27 points)** Plot the following functions using $2\ by\ 3$ subplots. Each plot must have its own title, and its own x and y labels. Make also sure that each plot enough of the function to show its behavior.
    * $f(x) = 3 x^2 + 10$
    * $f(x) = \frac{1}{1 + e^{-x}}$
    * $f(z) = max(\alpha z, z)$ where $\alpha = 0.01$ where $max(...)$ returns the maximum of its arguments.
    * $f(x) = sin(x^2)$
    * $f(x) = cos(x) + ln(x)$
    * $f(x) = tanh(x)$

In [12]:
# TODO

* **(3 points)** Save the plot into a file named `e01.png`.

In [13]:
# TODO